name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: cp .env.example .env.local
      - run: yarn build
