name: build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: cp .env.example .env.local
      - run: yarn build:ci
