name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts

      - name: Mirror to GitLab
        run: |
          git remote add mirror git@gitlab.com:screeb-otis/screeb-changelog.git
          git fetch --unshallow
          git push mirror master -f
